import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import { ReactElement, use } from 'react'
import type { NextPageWithLayout } from '../_app';
import { useAuthState } from 'react-firebase-hooks/auth'
import { auth, db } from '@/firebase'
import UserDetailScreen from '@/components/UserDetailScreen/UserDetailScreen';
import { useRouter } from 'next/router';
import getStatusFriend from '@/utils/getStatusFriend';

const inter = Inter({ subsets: ['latin'] })

// import '@/styles/tailwind.min.css'
const Page: NextPageWithLayout = ({userInfo}: any) => {

const [user] = useAuthState(auth);

  return (
    <>
      <Head>
        <title>Chatapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <UserDetailScreen userInfo={userInfo} statusFriend={getStatusFriend(user?.email!, userInfo?.id)} />
    </>
  )
}
 
Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};

export default Page;

export async function getServerSideProps(context: any) {

    const userDoc = await db.collection("users").doc(context.query.id).get();

    const userInfo: any = {
        id: userDoc?.id,
        ...userDoc?.data()
    }

    return {
        props: {
            userInfo: JSON.stringify(userInfo)
        }
    }
}

