import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import { ReactElement } from 'react'
import type { NextPageWithLayout } from '../_app';
import UserDetailScreen from '@/components/ProfilePage/UserDetailScreen/UserDetailScreen';
import { db } from '@/firebase';
import { GetStaticPaths } from 'next';

const inter = Inter({ subsets: ['latin'] })

// import '@/styles/tailwind.min.css'
const Page: NextPageWithLayout = ({userInfo}: any) => {

const data = JSON.parse(userInfo);

  return (
    <>
      <Head>
        <title>Chatapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <UserDetailScreen userInfo={data} />
    </>
  )
}
 
Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};

export default Page;

export async function getStaticProps({ params }: any) {

    const userDoc = await db.collection("users").doc(params.id).get();

    const userInfo: any = {
        id: userDoc?.id,
        ...userDoc?.data()
    }

    return {
        props: {
            userInfo: JSON.stringify(userInfo)
        }
    }
}

export async function getStaticPaths(){

  const userDoc = await db.collection("users").get();

  const paths = userDoc?.docs?.map((user) => ({
    params: { id: user.id.toString() },
  }))

  return {
      paths,
      fallback: false //indicates the type of fallback
  }
}

