import Head from 'next/head'
import { Inter } from 'next/font/google'
import SidebarMessage from '@/components/ChatPage/SidebarMessage/SidebarMessage'
import Layout from '@/components/Layout'
import { ReactElement, useEffect } from 'react'
import type { NextPageWithLayout } from './_app';
import ChatScreen from '@/components/ChatPage/ChatScreen/ChatScreen'
import sendNotificationFCM from '@/utils/sendNotificationFCM'

const inter = Inter({ subsets: ['latin'] })


// import '@/styles/tailwind.min.css'
const Page: NextPageWithLayout = () => {



  useEffect(() => {
    
  },[])

  const handleTestMessage = () => {
    sendNotificationFCM(
      "Hello world", 
      "First message", 
      "c51PFxRwFhvtErtWzn61Ca:APA91bFQAaPkzpBTEo9nCqwa-lZD4nNWvtQB1hLar9mtqPFiTB2ZCQD8kFHKX8Uqy8L5lGnMkbVqHjRlKfRQ3NNSyX6eoo1pC8fqEDZ4WJNPTsCd8x__jr4coimRCcAVJmy32XkC4zJ1",
      "ya29.a0AWY7Ckkl4Oq33t6H4JhuvFBDbIRe1B5Hl7Bbg8EmiO06Iy8XVI3etXj8b2_rpmxQ6hlYPwyjjoUNGlCnPjIv8Y7uCfSvZuqMVeOQB3mC8Fi50V584gWPXq1b4EXh9w8094Cov2_NQtgzYEooriyxcVg9w8qiaCgYKASASARMSFQG1tDrp2SdkcMQgtoEF1rhcQMYRBw0163"
    ).then((data) => console.log(data))
  }

  return (
    <>
      <Head>
        <title>Chatapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SidebarMessage /> */}
      <button onClick={handleTestMessage}>Test message</button>
        <div className="main flex-1 flex flex-col">
            <div className="hidden lg:block heading flex-2">
                <h1 className="text-3xl text-gray-700 mb-4">Chat</h1>
            </div>

            <div className="flex-1 flex h-full">
              
                <SidebarMessage />

            </div>
        </div>

    </>
  )
}
 
Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};

export default Page;
