import Head from 'next/head'
import { Inter } from 'next/font/google'
import SidebarMessage from '@/components/ChatPage/SidebarMessage/SidebarMessage'
import Layout from '@/components/Layout'
import { ReactElement, useContext, useEffect } from 'react'
import { GetStaticProps } from 'next'
import { getDataHooksProps } from 'next-data-hooks'
import { NextPageWithLayout } from './_app'
import sendNotificationFCM from '@/utils/sendNotificationFCM'
import { auth } from '@/firebase'
import { useAppContext } from '@/context/AppContext'


const inter = Inter({ subsets: ['latin'] })


// import '@/styles/tailwind.min.css'
const Page: NextPageWithLayout = () => {

  // const value: any = useAppContext()

  // const handleTestMessage = () => {
  //   // auth.signOut()
  //   sendNotificationFCM(
  //     "Hello world", 
  //     "First message", 
  //     value.fcm_token
  //   ).then((data) => console.log(data))
  // }

  // const handleShowUserDetail = async() => {

  // }

  return (
    <>
      <Head>
        <title>Chatapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="main flex-1 flex flex-col">
            <div className="hidden lg:block heading flex-2">
                <h1 className="text-3xl text-gray-700 mb-4">Chat</h1>
            </div>
            
            <div className="flex-1 flex h-full">
                {/* <button onClick={handleTestMessage}>adada</button> */}
                <SidebarMessage/>
            </div>
        </div>

    </>
  )
}
 
Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
};

export default Page;
