import SidebarSetting from "@/components/SidebarSetting/SidebarSetting";
import Head from "next/head";

function SettingPage() {

    return (
        <div>
          <Head>
            <title>Chatapp 2.0 - Setting Page</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <SidebarSetting />
        </div>
    )
}

export default SettingPage;