import { useAuthState } from "react-firebase-hooks/auth";
import { auth, db } from "@/firebase";
import { useState } from "react";
import Head from "next/head";
import SidebarContact from "@/components/SidebarContact/SidebarContact";

export default function ListFriend() {

    const [user] = useAuthState(auth);
    const [searchInput, setSearchInput] = useState('');

    // const friendSnapshot = getAllFriendCurrentUser(user?.uid);

    // const friendSnapshotFiltered = findFriendByKeyWord(searchInput, user?.uid);

// users {
//     email: ''
//     friends: [
//         {
//             uid: '',
//             userId: '',
//         },
//         {
//             uid: '',
//             userId: '',
//         }
//     ]
// }

// db.collection('friends').where('userId1','==',)

// friends {
//     userId1: '',
//     userId2: '',

// }

// requests_add_friend {
//     senderEmail,
//     recipientId,
//     isAccept,
//     isCancel
// }

// messages {
//     users: [

//     ],
//     message: '',
//     photoURL: '',
//     sentAt: '',
//     senderEmail: '',
//     isGroup: '',
// }

    // db.collection('users').doc('wrwrwrwrwwr').get().then((u) => {
    //     setSearchInput(u);
    // })

    return (
        
        <div>
            <Head>
                <title>Chatapp 2.0 - Contact Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
            </Head>
            <SidebarContact />
        </div>
    )
}


